import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Provider } from 'react-redux';

import { ErrorBoundary } from '@/components/ErrorBoundary/errorBoundary';
import { wrapper } from '@/redux/store';
import '@/styles/globals.css';

const App = ({ Component, ...rest }: AppProps) => {
  const { store, props } = wrapper.useWrappedStore(rest);
  return (
    <>
      <Head>
        <title>Anime Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ErrorBoundary>
        <Provider store={store}>
          <Component {...props.pageProps} />
        </Provider>
      </ErrorBoundary>
    </>
  );
};

export default App;
