import Head from 'next/head';
import { GetServerSideProps } from 'next';

import { wrapper } from '@/redux/store';
import { getAnimeDetail, getAnimeList, getRunningQueriesThunk } from '@/redux/services/animeService';
import { IData } from '@/types/types';
import Layout from '@/components/Layout/layout';
import AnimeList from '@/components/AnimeList/animeList';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  const { page, search, details, perPage } = context.query;

  const initialPageSize = perPage === '20' || perPage === '15' || perPage === '10' || perPage === '5';

  store.dispatch(
    getAnimeList.initiate({
      pageQuery: page?.toString() || '1',
      searchQuery: search?.toString() || '',
      initialPageSize: initialPageSize,
      perPageQuery: perPage?.toString() || '20',
    })
  );

  if (details) {
    store.dispatch(getAnimeDetail.initiate(details.toString()));
  }

  await Promise.all(store.dispatch(getRunningQueriesThunk()));

  return {
    props: {
      animeList: store.getState().animeDataReducer.animeList,
      animeDetails: store.getState().animeDataReducer.animeDetails,
    },
  };
});

const Home = (data: IData) => {
  return (
    <>
      <Head>
        <title>Anime Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AnimeList data={data} />
      </Layout>
    </>
  );
};

export default Home;
